### ISSUE TITLE
Cookie changed?

### ISSUE THREAD

**Issue by timriker** [Schamper/forza-rewards#2]
No matter which cookie I provide, as of this week I get "Token expired"
The web requests don't seem to include xlaWebAuth_1 anymore.

**Comment by Schamper** [comment]
That is correct, I noticed this myself a few weeks ago. I've been running an updated version locally but just updated the script in this repository: https://github.com/Schamper/forza-rewards/commit/47da336ffd1f7d7191e45b5d91433c82c426cfaa

I didn't really feel like figuring out which token to use, so now I just take the entire cookie string. I've been running this version for a few weeks with no issues now.

**Comment by timriker** [comment]
It works with just these two:
prod.Forza.UserId
__RequestVerificationToken

**Comment by timriker** [comment]
I'm now using these two:
prod.Forza.UserId
prod.Forza.RefreshToken

The __RequestVerificationToken seems to expire quickly now.

**Comment by Schamper** [comment]
Hm I've been unable to get it working again, even with a cookiejar instead of fixed cookies. Have you been more successful?

**Comment by timriker** [comment]
It worked once with that set, and now it's broken again. Someone is messing with the back end. I'll have to walk through it and see what's needed. Holler if you figure it out.

**Comment by timriker** [comment]
The web call hits:
https://rewards.forzamotorsport.net/en-us/redeem
with a POST containing
__RequestVerificationToken=<something>
I'm not sure where that value comes from.
after redeeming rewards, this works (values removed)
$HOME/bin/rewards.py 'prod.Forza.UserId=AA*_o; prod.Forza.RefreshToken=M.R3*y; __RequestVerificationToken=vx*1'
A get in the browser without a __RequestVerificationToken still works and gets that token as a cookie in reply. I'm not sure how it is working in the browser....
I wonder if we request /en-us/ first if we can then request the /en-us/redeem with some cookies that might get updated?

**Comment by Schamper** [comment]
I think it's just broken, since it also doesn't work anymore when I just revisit that page in my browser the next day, without interacting with a script in any way.

**Comment by timriker** [comment]
It's broken for me too. Each week I get a cookie expired email. Clear the cookies for *.forzamotorsport.net and it still works in the browser. Here's the sequence:

https://rewards.forzamotorsport.net/en-us/redeem

https://login.live.com/oauth20_authorize.srf?client_id=eb...6&scope=XboxLivePartner.Signin%20xboxlive.offline_access&response_type=code&redirect_uri=https%3a%2f%2frewards.forzamotorsport.net%2foauth%2fcallback&state=https%3a%2f%2frewards.forzamotorsport.net%2fen-us%2fredeem

https://rewards.forzamotorsport.net/oauth/callback?code=M....4&state=https://rewards.forzamotorsport.net/en-us/redeem

https://rewards.forzamotorsport.net/en-us/redeem

So it appears to be using some live.com cookies to authenticate now. We should be able to duplicate that if we can find the right cookies, follow the chain of redirects and present the correct cookie to live.com to get the updated cookie from callback and present to redeem.

If I remove the cookies for live.com forzamotorsport.net rewards.forzamotorsport.net and 3001.scriptcdn.net and refresh in a browser, the rewards page still loads. It looks like the ONLY cookies that are required now are the ones sent to login.live.com so if we cache those, then use what login.live.com gives us when following to callback and redeem, we should be good.

Still testing.

I can't get the second link to login.live.com to come back with a Location: header using curl. I'm not sure why. I export the curl command from Chrome, but it looks like it's filling in the wrong Referrer header, and perhaps more that I can't see yet.

**Comment by Schamper** [comment]
I haven't been able to get this working anymore and Forza Rewards is being discontinued later this year anyway: https://support.forzamotorsport.net/hc/en-us/articles/4405566679315-Forza-Rewards

I will archive this repository.
